apiVersion: v1
kind: Service
metadata:
  labels:
    app: teamspeak-db
    tier: teamspeak
  name: teamspeak-db
spec:
  ports:
    - name: "3306"
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: teamspeak-db
    tier: teamspeak
  type: ClusterIP

